import { sql } from 'drizzle-orm';
import {
  decimal,
  index,
  integer,
  jsonb,
  pgEnum,
  pgTable,
  timestamp,
  uniqueIndex,
  uuid,
  varchar,
} from 'drizzle-orm/pg-core';

import { auditColumns, baseColumns, softDeleteColumn } from './_base';

/**
 * BE-26 — Goods Receipt Note (GRN).
 *
 * Three tables ship in one file because they share lifecycle and one
 * migration: the line items cascade-delete with the header, and the
 * append-only event log only ever reads against the header by id.
 *
 * Workflow:  draft → pending_review → posted → reversed
 *                   ↘ cancelled (only from non-posted states)
 *
 * Posting is the one transition that touches expiry tracking (BE-18),
 * supplier performance (BE-25), and inventory (BE-27 — once it lands).
 * Reversal undoes inventory + expiry effects but never deletes the
 * original — it stamps `reversedAt` / `reversalReason` and moves
 * status to `reversed`. Cancellation is only allowed before posting.
 *
 * Indexes target the hot read paths:
 *   - `(tenantId, storeId, status, inwardDate)` for the manager
 *     "what came in this week" dashboard,
 *   - `(supplierId, inwardDate)` for vendor scorecards,
 *   - `(invoiceNumber, supplierId)` UNIQUE so the same invoice can't
 *     be entered twice for the same supplier — a hard validation
 *     guarantee at the storage layer.
 */

export const grnStatusEnum = pgEnum('grn_status', [
  'draft',
  'pending_review',
  'posted',
  'cancelled',
  'reversed',
]);

export const grnEventTypeEnum = pgEnum('grn_event_type', [
  'created',
  'updated',
  'item_added',
  'item_updated',
  'item_removed',
  'submitted_for_review',
  'approved',
  'posted',
  'cancelled',
  'reversed',
]);

export const grnHeaders = pgTable(
  'grn_headers',
  {
    ...baseColumns,
    ...softDeleteColumn,
    ...auditColumns,
    tenantId: uuid('tenant_id').notNull(),
    storeId: uuid('store_id').notNull(),

    /** Auto-generated by `GrnNumberGenerator`. Format `GRN-<store6>-YYYYMM-NNNN`. */
    grnNumber: varchar('grn_number', { length: 50 }).notNull(),

    supplierId: uuid('supplier_id').notNull(),

    invoiceNumber: varchar('invoice_number', { length: 100 }).notNull(),
    invoiceDate: timestamp('invoice_date', { withTimezone: true }).notNull(),
    poNumber: varchar('po_number', { length: 100 }),

    inwardDate: timestamp('inward_date', { withTimezone: true }).notNull(),
    expectedDeliveryDate: timestamp('expected_delivery_date', { withTimezone: true }),
    orderDate: timestamp('order_date', { withTimezone: true }),

    status: grnStatusEnum('status').notNull().default('draft'),

    // Amounts kept as strings (decimal) — Drizzle returns string for numeric
    // columns and BE-26 explicitly avoids accounting semantics. These
    // are vendor-accountability fields.
    subtotal: decimal('subtotal', { precision: 14, scale: 2 }),
    taxAmount: decimal('tax_amount', { precision: 14, scale: 2 }),
    totalAmount: decimal('total_amount', { precision: 14, scale: 2 }),

    // Denormalised stats — refreshed by the service layer on every write
    // so list / dashboard queries don't need a join + GROUP BY.
    totalItems: integer('total_items').notNull().default(0),
    totalQuantity: integer('total_quantity').notNull().default(0),
    minExpiryRemainingDays: integer('min_expiry_remaining_days'),
    shortShelfLifeCount: integer('short_shelf_life_count').notNull().default(0),

    postedAt: timestamp('posted_at', { withTimezone: true }),
    postedBy: uuid('posted_by'),

    cancelledAt: timestamp('cancelled_at', { withTimezone: true }),
    cancelledBy: uuid('cancelled_by'),
    cancellationReason: varchar('cancellation_reason', { length: 500 }),

    reversedAt: timestamp('reversed_at', { withTimezone: true }),
    reversedBy: uuid('reversed_by'),
    reversalReason: varchar('reversal_reason', { length: 500 }),

    notes: varchar('notes', { length: 2000 }),
    metadata: jsonb('metadata').$type<Record<string, unknown>>().default({}),
  },
  (t) => ({
    tenantStoreStatusDateIdx: index('idx_grn_tenant_store_status_date').on(
      t.tenantId,
      t.storeId,
      t.status,
      t.inwardDate,
    ),
    supplierDateIdx: index('idx_grn_supplier_date').on(t.supplierId, t.inwardDate),
    invoiceIdx: index('idx_grn_invoice').on(t.invoiceNumber),
    statusIdx: index('idx_grn_status').on(t.status),
    grnNumberUniq: uniqueIndex('uniq_grn_number_tenant').on(t.tenantId, t.grnNumber),
    invoiceSupplierUniq: uniqueIndex('uniq_grn_invoice_supplier').on(t.supplierId, t.invoiceNumber),
  }),
);

export type GrnHeaderRow = typeof grnHeaders.$inferSelect;
export type NewGrnHeader = typeof grnHeaders.$inferInsert;

export const grnItems = pgTable(
  'grn_items',
  {
    ...baseColumns,
    grnId: uuid('grn_id')
      .notNull()
      .references(() => grnHeaders.id, { onDelete: 'cascade' }),
    tenantId: uuid('tenant_id').notNull(),
    storeId: uuid('store_id').notNull(),

    /** Resolved during posting if absent at draft time. */
    productId: uuid('product_id'),
    ean: varchar('ean', { length: 13 }).notNull(),
    /** Snapshot of the product name at receipt — immutable audit field. */
    productNameSnapshot: varchar('product_name_snapshot', { length: 200 }),

    quantity: integer('quantity').notNull(),
    unit: varchar('unit', { length: 20 }).notNull().default('pcs'),

    batchNumber: varchar('batch_number', { length: 100 }),
    manufactureDate: timestamp('manufacture_date', { withTimezone: true }),
    expiryDate: timestamp('expiry_date', { withTimezone: true }),
    /** Computed at draft time and refreshed at post time. */
    expiryRemainingDays: integer('expiry_remaining_days'),

    unitPrice: decimal('unit_price', { precision: 10, scale: 2 }),
    taxPercent: decimal('tax_percent', { precision: 5, scale: 2 }),
    totalPrice: decimal('total_price', { precision: 14, scale: 2 }),

    /** Linkages populated at posting time. */
    expiryRecordId: uuid('expiry_record_id'),
    inventoryItemId: uuid('inventory_item_id'),
    stockMovementId: uuid('stock_movement_id'),

    notes: varchar('notes', { length: 500 }),
    metadata: jsonb('metadata').$type<Record<string, unknown>>().default({}),
  },
  (t) => ({
    grnIdx: index('idx_grn_items_grn').on(t.grnId),
    eanIdx: index('idx_grn_items_ean').on(t.ean),
    productIdx: index('idx_grn_items_product').on(t.productId),
    batchIdx: index('idx_grn_items_batch').on(t.batchNumber),
    /**
     * Storage-level guard: same EAN + same batch can't be added twice
     * to the same GRN. Keeps the validator's "duplicate batch" warning
     * honest.
     */
    grnEanBatchUniq: uniqueIndex('uniq_grn_item_grn_ean_batch')
      .on(t.grnId, t.ean, t.batchNumber)
      .where(sql`batch_number IS NOT NULL`),
  }),
);

export type GrnItemRow = typeof grnItems.$inferSelect;
export type NewGrnItem = typeof grnItems.$inferInsert;

export const grnEvents = pgTable(
  'grn_events',
  {
    ...baseColumns,
    grnId: uuid('grn_id')
      .notNull()
      .references(() => grnHeaders.id, { onDelete: 'cascade' }),
    tenantId: uuid('tenant_id').notNull(),
    type: grnEventTypeEnum('type').notNull(),
    actorId: uuid('actor_id').notNull(),
    notes: varchar('notes', { length: 1000 }),
    metadata: jsonb('metadata').$type<Record<string, unknown>>().default({}),
  },
  (t) => ({
    grnCreatedIdx: index('idx_grn_events_grn_created').on(t.grnId, t.createdAt),
    typeIdx: index('idx_grn_events_type').on(t.type),
    tenantIdx: index('idx_grn_events_tenant').on(t.tenantId),
  }),
);

export type GrnEventRow = typeof grnEvents.$inferSelect;
export type NewGrnEvent = typeof grnEvents.$inferInsert;
